"""Display labels for the keys and enumerated values that analyzers put in report sections and finding evidence.

Analyzers store machine-readable keys (``days_present``, ``p50_seconds``) and enumerated values (``investigate``,
``never_connected``, ``no_stats``) in ``Report.sections`` and ``Finding.evidence``. The renderers never show
those raw: every key and every known value is translated here, in English and Spanish, and registered as

* ``report.ev.<key>`` — the label of an evidence/section key;
* ``report.ev.<parent>.<key>`` — the label of a key nested under ``<parent>`` when it means something else
  there (``window.days`` is the elapsed time, ``gates.burst`` a safety gate);
* ``report.val.<value>`` / ``report.val.<key>.<value>`` — the label of an enumerated value (the second form
  when the same word means different things under different keys).

Spanish is neutral Latin American Spanish with formal "usted"; the terms follow the rest of the catalogs
("supresión", "ajuste", "vencida", "monitoreable", "archivo", "degradar").
"""

from __future__ import annotations

from ..i18n import register

__all__ = ["ENUM_KEYS", "EVIDENCE_LABELS", "SCOPED_LABELS", "VALUE_LABELS"]

# key -> (English, Spanish)
EVIDENCE_LABELS: dict[str, tuple[str, str]] = {
    # generic
    "observed": ("Observed", "Observado"),
    "expected": ("Expected", "Esperado"),
    "p": ("p-value", "Valor p"),
    "p0": ("P(no events)", "P(sin eventos)"),
    "p_value": ("p-value", "Valor p"),
    "pvalue": ("p-value", "Valor p"),
    "q": ("Adjusted p-value (q)", "Valor p ajustado (q)"),
    "gap": ("Gap", "Hueco"),
    "gap_hours": ("Gap (hours)", "Hueco (horas)"),
    "gap_seconds": ("Gap", "Hueco"),
    "last_seen": ("Last seen", "Visto por última vez"),
    "first_seen": ("First seen", "Visto por primera vez"),
    "duty": ("Activity pattern", "Patrón de actividad"),
    "tier": ("Tier", "Criticidad"),
    "share": ("Share", "Proporción"),
    "per_day": ("Per day", "Por día"),
    "total": ("Total", "Total"),
    "level": ("Level", "Nivel"),
    "levels": ("By level", "Por nivel"),
    "rule_id": ("Rule", "Regla"),
    "rule": ("Rule", "Regla"),
    "rules": ("Rules", "Reglas"),
    "rule_level": ("Rule level", "Nivel de la regla"),
    "agent": ("Agent", "Agente"),
    "agents": ("Agents", "Agentes"),
    "agents_affected": ("Agents affected", "Agentes afectados"),
    "agents_truncated": ("Agent list truncated", "Lista de agentes truncada"),
    "agent_id": ("Agent ID", "ID del agente"),
    "agent_status": ("Agent status", "Estado del agente"),
    "host": ("Host", "Equipo"),
    "hosts": ("Hosts", "Equipos"),
    "hosts_total": ("Hosts in total", "Equipos en total"),
    "count": ("Count", "Cantidad"),
    "days": ("Days", "Días"),
    "days_active": ("Days active", "Días activos"),
    "days_present": ("Days present", "Días con actividad"),
    "days_elapsed": ("Days elapsed", "Días transcurridos"),
    "dates": ("Calendar days", "Días de calendario"),
    "window": ("Window", "Ventana"),
    "start": ("Start", "Inicio"),
    "end": ("End", "Fin"),
    "baseline": ("Baseline", "Línea base"),
    "ratio": ("Ratio", "Cociente"),
    "hidden_per_day": ("Demoted per day", "Degradadas por día"),
    "hidden_total": ("Demoted in total", "Degradadas en total"),
    "share_of_rule": ("Share of rule", "Proporción de la regla"),
    "hidden_analyst_facing": ("Analyst-facing demoted", "Degradadas visibles para analistas"),
    "analyst_facing": ("Analyst-facing", "Para analistas"),
    "clusters": ("Clusters", "Clústeres"),
    "clusters_per_day": ("Clusters per day", "Clústeres por día"),
    "dependents": ("Dependent rules", "Reglas dependientes"),
    "dependents_verified": ("Dependents verified against the ruleset", "Dependencias verificadas en el ruleset"),
    "conditions": ("Conditions", "Condiciones"),
    "expires": ("Expires", "Vence"),
    "reproduce": ("Reproduce", "Reproducir"),
    "query": ("Query", "Consulta"),
    "filter": ("Filter", "Filtro"),
    "from": ("From", "Desde"),
    "to": ("To", "Hasta"),
    "missing_fields": ("Missing fields", "Campos faltantes"),
    "examples": ("Examples", "Ejemplos"),
    "precursor": ("Precursor", "Precursor"),
    "precursors": ("Precursors", "Precursores"),
    "technique": ("ATT&CK technique", "Técnica ATT&CK"),
    "techniques": ("ATT&CK techniques", "Técnicas ATT&CK"),
    "mitre": ("ATT&CK", "ATT&CK"),
    "log_source": ("Log source", "Fuente de logs"),
    "log_sources": ("Log sources", "Fuentes de logs"),
    "source": ("Source", "Fuente"),
    "sources": ("Sources", "Fuentes"),
    "status": ("Status", "Estado"),
    "state": ("State", "Situación"),
    "last_keepalive": ("Last keepalive", "Último keepalive"),
    "last_event": ("Last event", "Último evento"),
    "lag_p95": ("Lag p95", "Retraso p95"),
    "future_timestamps": ("Future timestamps", "Marcas de tiempo futuras"),
    "bad_timestamps": ("Unparseable timestamps", "Marcas de tiempo ilegibles"),
    "malformed": ("Malformed records", "Registros mal formados"),
    "sampled": ("Sampled", "Muestreado"),
    "truncated": ("Truncated", "Truncado"),
    "partial_failures": ("Partial failures", "Fallos parciales"),
    "partial_failure_examples": ("Examples of partial failures", "Ejemplos de fallos parciales"),
    "triggers": ("Triggered by", "Motivos"),
    "not_evaluated": ("Not evaluated", "No evaluado"),
    "dropped": ("Dropped", "Descartados"),
    "fp_rate": ("False-positive rate", "Tasa de falsos positivos"),
    "dispositions": ("Dispositions", "Disposiciones"),
    "action": ("Action", "Acción"),
    "review_required": ("Review required", "Requiere revisión"),
    "alpha": ("Alarm threshold (α)", "Umbral de alarma (α)"),
    "alpha_eff": ("Alarm threshold (α)", "Umbral de alarma (α)"),
    "presence_before": ("Presence before", "Presencia antes"),
    "presence_after": ("Presence after", "Presencia después"),
    "field": ("Field", "Campo"),
    "fields": ("Fields", "Campos"),
    "value": ("Value", "Valor"),
    "events": ("Events", "Eventos"),
    "file": ("File", "Archivo"),
    "files": ("Files", "Archivos"),
    "path": ("Path", "Ruta"),
    "paths": ("Paths", "Rutas"),
    "line": ("Line", "Línea"),
    "platform": ("Platform", "Plataforma"),
    "platforms": ("Platforms", "Plataformas"),
    "peers": ("Peers", "Pares"),
    "peer_share": ("Share of peers", "Proporción de pares"),
    "contract": ("Contract", "Contrato"),
    "event_code": ("Event code", "Código de evento"),
    "code": ("Event code", "Código de evento"),
    "anchor_code": ("Reference event code", "Código de evento de referencia"),
    "channel": ("Channel", "Canal"),
    "missing": ("Missing", "Ausentes"),
    "version": ("Version", "Versión"),
    "daily": ("Daily counts", "Conteos diarios"),
    "series": ("Series", "Serie"),
    "reporting": ("Reporting", "Reportando"),
    "peer_group": ("Peer group", "Grupo de pares"),
    "peer_comparable": ("Comparable with peers", "Comparables con pares"),
    "inventory": ("Inventory", "Inventario"),
    "matched": ("Matched", "Coincidentes"),
    "present": ("Present", "Presentes"),
    "silent": ("Silent", "Silenciosas"),
    "low": ("Low volume", "Volumen bajo"),
    "not_assessed": ("Not assessed / explained", "No evaluado / explicado"),
    "not_assessed_hosts": ("Hosts not assessed", "Equipos no evaluados"),
    "basis": ("Basis", "Base"),
    "name": ("Name", "Nombre"),
    "description": ("Description", "Descripción"),
    "min_events_per_day": ("Min. events/day", "Mín. eventos/día"),
    "hidden": ("Demoted", "Degradadas"),
    "hidden_high": ("High-level demoted", "Degradadas de nivel alto"),
    "tp_hidden": ("True positives demoted", "Verdaderos positivos degradados"),
    "hidden_unknown_level": ("Demoted with unknown level", "Degradadas de nivel desconocido"),
    "hidden_external": ("Demoted from public addresses", "Degradadas de direcciones públicas"),
    "share_of_analyst_facing": ("Share of analyst-facing", "Proporción para analistas"),
    "analyst_facing_clusters_per_day": ("Analyst-facing clusters per day", "Clústeres para analistas por día"),
    "novel_actors": ("New actors", "Actores nuevos"),
    "novel_hosts": ("New hosts", "Equipos nuevos"),
    "co_occurring": ("Co-occurring with high-level alerts", "Coincidentes con alertas de nivel alto"),
    "beacon_hits": ("Beacon-like destinations", "Destinos con patrón de beacon"),
    "sustained_hits": ("Sustained public activity", "Actividad pública sostenida"),
    "backtest": ("Backtest", "Backtest"),
    "gates": ("Safety gates", "Controles de seguridad"),
    "verdict": ("Verdict", "Veredicto"),
    "verdicts": ("Verdicts", "Veredictos"),
    "verdict_counts": ("Verdicts", "Veredictos"),
    "verdict_scoped": ("Verdict for a scope of the rule", "Veredicto para un alcance de la regla"),
    "top_anchor": ("Top anchor", "Ancla principal"),
    "anchor": ("Anchor", "Ancla"),
    # noise
    "suggestion": ("Suggestion ID", "ID de la sugerencia"),
    "suggestions": ("Suggestion IDs", "IDs de las sugerencias"),
    "alerts": ("Alerts", "Alertas"),
    "alerts_upper_bound": ("Alerts (upper bound)", "Alertas (cota superior)"),
    "alerts_per_day": ("Alerts per day", "Alertas por día"),
    "analyst_facing_per_day_estimate": ("Analyst-facing per day (estimate)", "Para analistas por día (estimación)"),
    "co_occurrence": ("Also in high-level alerts", "También en alertas de nivel alto"),
    "beacons": ("Beacon-like destinations", "Destinos con patrón de beacon"),
    "public_sources": ("Public sources", "Orígenes públicos"),
    "impact": ("Impact", "Impacto"),
    "fix": ("Where to fix", "Dónde corregir"),
    "ignore_pattern": ("Ignore pattern (agent.conf)", "Patrón para ignorar (agent.conf)"),
    "entity": ("Entity", "Entidad"),
    "active_hours": ("Active hours", "Horas activas"),
    "span_hours": ("Span (hours)", "Lapso (horas)"),
    "outbound": ("Outbound", "Saliente"),
    "regularity": ("Regularity", "Regularidad"),
    "beaconing": ("Beaconing", "Beaconing"),
    "options": ("Options", "Opciones"),
    "noisy_threshold": ("Noisy threshold", "Umbral de ruido"),
    "noisy": ("Noisy", "Ruidosa"),
    "backtested": ("Backtested", "Verificado con backtest"),
    "learning": ("Learning", "En aprendizaje"),
    "safe_tuning_candidates": ("Safe tuning candidates", "Candidatos de ajuste seguros"),
    "review_required_candidates": ("Candidates that require review", "Candidatos que requieren revisión"),
    "index_volume_candidates": ("Index-volume-only candidates", "Candidatos solo de volumen del índice"),
    "skipped_events": ("Events without a rule (skipped)", "Eventos sin regla (omitidos)"),
    "time_saved_minutes_per_day": ("Time saved (min/day, upper bound)", "Tiempo ahorrado (min/día, máximo)"),
    "time_saved_kind": ("Time saved (kind)", "Tiempo ahorrado (tipo)"),
    "totals": ("Totals", "Totales"),
    "top5_share": ("Share of the top 5 rules", "Proporción de las 5 reglas principales"),
    "suppressions_file": ("Suppressions file", "Archivo de supresiones"),
    # silence
    "expected_in_gap": ("Expected during the gap", "Esperados durante el hueco"),
    "baseline_days": ("Baseline days", "Días de línea base"),
    "model": ("Baseline model", "Modelo de línea base"),
    "rate_per_hour": ("Events per hour (baseline)", "Eventos por hora (línea base)"),
    "dispersion_k": ("Dispersion k (hourly)", "Dispersión k (por hora)"),
    "dispersion_k_day": ("Dispersion k (daily)", "Dispersión k (diaria)"),
    "day_sigma": ("Day-to-day variation (σ)", "Variación entre días (σ)"),
    "off_day_probability": ("Probability of a day off", "Probabilidad de un día sin actividad"),
    "off_day_persistence": ("Days off in a row", "Días seguidos sin actividad"),
    "low_day_probability": ("Probability of a low day", "Probabilidad de un día bajo"),
    "t_min_hours": ("Shortest detectable silence (hours)", "Silencio mínimo detectable (horas)"),
    "frozen_baseline": ("Baseline frozen", "Línea base congelada"),
    "burstiness": ("Burstiness", "Irregularidad (ráfagas)"),
    "explained": ("Also explains", "También explica"),
    "explained_count": ("Findings explained", "Hallazgos explicados"),
    "silent_hours": ("Silent for (hours)", "En silencio (horas)"),
    "threshold_hours": ("Threshold (hours)", "Umbral (horas)"),
    "sla_hours": ("SLA (hours)", "SLA (horas)"),
    "disconnected_hours": ("Disconnected for (hours)", "Desconectado (horas)"),
    "sources_alive": ("Sources still sending", "Fuentes que siguen enviando"),
    "keys": ("Keys", "Claves"),
    "keys_evaluated": ("Keys evaluated", "Claves evaluadas"),
    "variant": ("Variant", "Variante"),
    "criteria": ("Criteria", "Criterios"),
    "name_patterns": ("Host name patterns", "Patrones de nombre de equipo"),
    "min_expected_events": ("Min. events expected", "Mín. de eventos esperados"),
    "threshold": ("Threshold", "Umbral"),
    "check": ("Check", "Control"),
    "checks": ("Checks", "Controles"),
    "fields_lost": ("Fields lost", "Campos perdidos"),
    "fields_tracked": ("Fields tracked", "Campos monitoreados"),
    "lost": ("Fields lost", "Campos perdidos"),
    "volume_ratio": ("Volume ratio (after / before)", "Cociente de volumen (después / antes)"),
    "detection_relevant": ("Used by detections", "Usado por detecciones"),
    "before": ("Presence before", "Presencia antes"),
    "after": ("Presence after", "Presencia después"),
    "events_before": ("Events before", "Eventos antes"),
    "events_after": ("Events after", "Eventos después"),
    "since": ("Since", "Desde"),
    "ts": ("Time", "Hora"),
    "overflow_events": ("Events over the cap", "Eventos por encima del límite"),
    "dropped_days": ("Days dropped", "Días descartados"),
    "alarm_budget": ("Alarm budget (false alarms per run)", "Presupuesto de alarmas (falsas alarmas por ejecución)"),
    "evaluated_until": ("Evaluated until", "Evaluado hasta"),
    "sources_truncated": ("Source list truncated", "Lista de fuentes truncada"),
    "input_kind": ("Input kind", "Tipo de entrada"),
    "alerts_only": ("Alerts only", "Solo alertas"),
    "cube_truncated": ("Baselines truncated", "Líneas base truncadas"),
    "precursors_truncated": ("Precursor list truncated", "Lista de precursores truncada"),
    "status_counts": ("Status counts", "Conteo por estado"),
    "monitorability": ("Monitorability", "Monitoreabilidad"),
    "critical_total": ("Critical sources", "Fuentes críticas"),
    "critical_monitorable": ("Critical sources monitorable", "Fuentes críticas monitoreables"),
    # coverage
    "status_reasons": ("Status reasons", "Motivos del estado"),
    "history_days": ("History (days)", "Historial (días)"),
    "min_history_days": ("Minimum history (days)", "Historial mínimo (días)"),
    "gaps_not_assessed": ("Gaps not assessed", "Brechas no evaluadas"),
    "peer_gaps": ("Gaps against peers", "Brechas frente a pares"),
    "peer_gaps_not_assessed": ("Gaps against peers not assessed", "Brechas frente a pares no evaluadas"),
    "peer_coverage": ("Coverage against peers", "Cobertura frente a pares"),
    "event_types": ("Event types", "Tipos de evento"),
    "api": ("In the Wazuh API", "En la API de Wazuh"),
    "api_only": ("In the API only (no data)", "Solo en la API (sin datos)"),
    "data_only": ("In the data only (not in the API)", "Solo en los datos (no en la API)"),
    "relayed": ("Relayed through another agent", "Retransmitidos por otro agente"),
    "by_status": ("By status", "Por estado"),
    "counters": ("Counters", "Contadores"),
    "unattributed_events": ("Events without an agent", "Eventos sin agente"),
    "stopped": ("Stopped", "Se detuvieron"),
    "assessed": ("Assessed", "Evaluado"),
    "expected_sources": ("Expected sources", "Fuentes esperadas"),
    "matrix_total": ("Agents in the matrix", "Agentes en la matriz"),
    "matrix_truncated": ("Matrix truncated", "Matriz truncada"),
    # pipeline
    "data_end": ("Newest event", "Evento más reciente"),
    "now_origin": ("Reference “now”", "Referencia de «ahora»"),
    "age_hours": ("Data age (hours)", "Antigüedad de los datos (horas)"),
    "reason": ("Reason", "Motivo"),
    "daemons": ("Daemons", "Demonios"),
    "threshold_seconds": ("Lag threshold", "Umbral de retraso"),
    "sources_assessed": ("Sources assessed", "Fuentes evaluadas"),
    "lagging": ("Lagging", "Con retraso"),
    "clock_ahead": ("Clock ahead", "Reloj adelantado"),
    "tz_offset": ("Timezone offset", "Desfase de zona horaria"),
    "worst": ("Slowest sources", "Fuentes más lentas"),
    "samples": ("Samples", "Muestras"),
    "p50_seconds": ("Median lag", "Retraso mediano"),
    "p95_seconds": ("Lag p95", "Retraso p95"),
    "kind": ("Kind", "Tipo"),
    # tuning audit
    "rules_parsed": ("Rules parsed", "Reglas analizadas"),
    "local_rules": ("Local rules", "Reglas locales"),
    "risky": ("Risky suppressions", "Supresiones riesgosas"),
    "risky_high": ("High-risk suppressions", "Supresiones de alto riesgo"),
    "expired": ("Expired suppressions", "Supresiones vencidas"),
    "parse_errors": ("Rule files that failed to parse", "Archivos de reglas con errores de análisis"),
    "duplicate_ids": ("Duplicate rule IDs", "IDs de regla duplicados"),
    "local_files": ("Local rule files", "Archivos de reglas locales"),
    "stock_rules_loaded": ("Stock rules loaded", "Reglas de fábrica cargadas"),
    "correlation_verified": ("Correlation dependencies verified", "Dependencias de correlación verificadas"),
    "parents": ("Parent rules", "Reglas padre"),
    "parents_total": ("Parent rules in total", "Reglas padre en total"),
    "overwrite": ("Overwrites a rule", "Sobrescribe una regla"),
    "days_overdue": ("Days overdue", "Días desde el vencimiento"),
    "date_add": ("Added on", "Agregada el"),
    # assessment
    "learning_keys": ("Keys still learning", "Claves aún en aprendizaje"),
}

# (parent, key) -> (English, Spanish): the meaning of a key under a given parent
SCOPED_LABELS: dict[tuple[str, str], tuple[str, str]] = {
    ("window", "days"): ("Days elapsed", "Días transcurridos"),
    ("window", "dates"): ("Calendar days", "Días de calendario"),
    ("gates", "share"): ("Share of the rule", "Proporción de la regla"),
    ("gates", "level"): ("Rule level", "Nivel de la regla"),
    ("gates", "tp"): ("True positives", "Verdaderos positivos"),
    ("gates", "novelty"): ("Novelty", "Novedad"),
    ("gates", "persistence"): ("Persistence", "Persistencia"),
    ("gates", "burst"): ("Bursts", "Picos"),
    ("gates", "co_occurrence"): ("High-level alerts on the same entities", "Alertas altas en las mismas entidades"),
    ("gates", "sensitive"): ("Sensitive rule", "Regla sensible"),
    ("gates", "dependents"): ("Correlation rules that depend on it", "Reglas de correlación dependientes"),
    ("gates", "external"): ("Public addresses", "Direcciones públicas"),
    ("gates", "beacon"): ("Beacon-like traffic", "Tráfico con patrón de beacon"),
    ("gates", "attacker_field"): ("Attacker-controllable scope", "Alcance controlable por un atacante"),
    ("dispositions", "tp"): ("True positives", "Verdaderos positivos"),
    ("dispositions", "fp"): ("False positives", "Falsos positivos"),
    ("dispositions", "btp"): ("Benign true positives", "Verdaderos positivos benignos"),
    ("dispositions", "duplicate"): ("Duplicates", "Duplicados"),
    ("dispositions", "untriaged"): ("Untriaged", "Sin triaje"),
    ("dispositions", "triaged"): ("Triaged", "Con triaje"),
    ("dispositions", "fp_lower_bound"): (
        "False-positive rate (lower bound)",
        "Tasa de falsos positivos (cota inferior)",
    ),
    ("noisy_threshold", "alerts"): ("Min. alerts", "Mín. de alertas"),
    ("noisy_threshold", "per_day"): ("Min. alerts per day", "Mín. de alertas por día"),
    ("agents", "inventory"): ("In the inventory", "En el inventario"),
    ("fields", "hosts"): ("Hosts", "Equipos"),
    ("fields", "events"): ("Events", "Eventos"),
    ("counters", "peer_gaps_not_assessed"): ("Gaps against peers not assessed", "Brechas frente a pares no evaluadas"),
    ("platforms", "hosts"): ("Hosts", "Equipos"),
    ("platforms", "expected"): ("Expected sources", "Fuentes esperadas"),
    ("assessment.learning", "learning"): ("Keys still learning", "Claves aún en aprendizaje"),
}

# Keys whose string values are enumerations (translated through report.val.*); other strings are data.
ENUM_KEYS: frozenset[str] = frozenset(
    {
        "verdict",
        "action",
        "impact",
        "fix",
        "status",
        "agent_status",
        "state",
        "variant",
        "kind",
        "reason",
        "model",
        "duty",
        "tier",
        "level",
        "platform",
        "input_kind",
        "basis",
        "now_origin",
        "time_saved_kind",
        "check",
        "checks",
        "status_reasons",
        "triggers",
        "not_evaluated",
    }
)

# value -> (English, Spanish), or "<key>.<value>" when the word depends on the key
VALUE_LABELS: dict[str, tuple[str, str]] = {
    # verdicts / actions
    "tune": ("Tune", "Ajustar"),
    "investigate": ("Investigate", "Investigar"),
    "fix_at_source": ("Fix at source", "Corregir en origen"),
    "aggregate": ("Aggregate", "Agregar"),
    "do_not_tune": ("Do not tune", "No ajustar"),
    "watch": ("Watch", "Vigilar"),
    "learning": ("Learning", "Aprendiendo"),
    "demote": ("Demote", "Degradar"),
    "review": ("Review before deploying", "Revisar antes de desplegar"),
    "impact.analyst": ("Analyst workload", "Carga de los analistas"),
    "impact.index_volume": (
        "Index volume only (no analyst sees them)",
        "Solo volumen del índice (ningún analista las ve)",
    ),
    "fix.fim": ("File integrity monitoring (ignore in agent.conf)", "Monitoreo de integridad (ignorar en agent.conf)"),
    "time_saved_kind.upper_bound_estimate": ("Upper-bound estimate", "Estimación máxima"),
    # agent statuses
    "active": ("Active", "Activo"),
    "disconnected": ("Disconnected", "Desconectado"),
    "never_connected": ("Never connected", "Nunca conectado"),
    "pending": ("Pending", "Pendiente"),
    # generic statuses (checks, sections)
    "ok": ("OK", "OK"),
    "warn": ("Warning", "Advertencia"),
    "fail": ("Problem", "Problema"),
    "not_assessed": ("Not assessed", "No evaluado"),
    # coverage states / variants / reasons
    "state.missing": ("Missing", "Ausente"),
    "state.silent": ("Silent", "Silenciosa"),
    "state.low": ("Low volume", "Volumen bajo"),
    "variant.never": ("Never sent", "Nunca se envió"),
    "variant.stopped": ("Stopped", "Se detuvo"),
    "short_history": ("History shorter than the minimum", "Historial más corto que el mínimo"),
    "gaps_not_assessed": ("Some gaps could not be assessed", "Algunas brechas no se pudieron evaluar"),
    "basis.contract": ("Contract", "Contrato"),
    "basis.peers": ("Peers", "Pares"),
    "contract": ("Contract", "Contrato"),
    "peers": ("Peers", "Pares"),
    # event-type checks
    "win_4688": ("Windows process creation (4688)", "Creación de procesos de Windows (4688)"),
    "sysmon_1": ("Sysmon process creation (1)", "Creación de procesos de Sysmon (1)"),
    "sysmon_3": ("Sysmon network connections (3)", "Conexiones de red de Sysmon (3)"),
    "ps_4104": ("PowerShell script blocks (4104)", "Bloques de script de PowerShell (4104)"),
    # platforms
    "windows": ("Windows", "Windows"),
    "linux": ("Linux", "Linux"),
    "macos": ("macOS", "macOS"),
    "darwin": ("macOS", "macOS"),
    "network": ("Network devices", "Dispositivos de red"),
    "unknown": ("Unknown", "Desconocida"),
    # ingest lag
    "kind.ok": ("OK", "OK"),
    "kind.lag": ("Lagging", "Con retraso"),
    "kind.ahead": ("Clock ahead", "Reloj adelantado"),
    "kind.tz_offset": ("Timezone offset", "Desfase de zona horaria"),
    # manager daemons
    "no_stats": (
        "Wazuh manager statistics were not available (no API or no permission)",
        "No hubo estadísticas del manager de Wazuh (sin API o sin permiso)",
    ),
    "unrecognized_shape": ("Unrecognized statistics format", "Formato de estadísticas no reconocido"),
    # silence models
    "hour_of_day": ("Hour of day", "Hora del día"),
    "hour_of_week": ("Hour of week", "Hora de la semana"),
    # source levels
    "level.tenant": ("Tenant", "Cliente"),
    "level.log_source": ("Log source", "Fuente de logs"),
    "level.agent": ("Agent", "Agente"),
    "level.agent_log_source": ("Agent · log source", "Agente · fuente de logs"),
    "level.rule": ("Rule", "Regla"),
    # assessment triggers
    "partial_failures": ("Partial failures", "Fallos parciales"),
    "truncated": ("Caps hit", "Límites alcanzados"),
    "no_events": ("No events", "Sin eventos"),
    "bad_timestamps": ("Unparseable timestamps", "Marcas de tiempo ilegibles"),
    "malformed": ("Malformed records", "Registros mal formados"),
    # tuning audit checks
    "attacker_only": ("Only attacker-controllable conditions", "Solo condiciones controlables por un atacante"),
    "breaks_correlation": ("Breaks correlation rules", "Rompe reglas de correlación"),
    "broad_network": ("Broad network range", "Rango de red amplio"),
    "correlation_unverified": ("Correlation not verified", "Correlación no verificada"),
    "high_level_parent": ("High-level parent rule", "Regla padre de nivel alto"),
    "missing_parent": ("Parent rule not loaded", "Regla padre no cargada"),
    "no_description": ("No description", "Sin descripción"),
    "overwrite_groups": ("Overwrite drops groups", "La sobrescritura quita grupos"),
    "overwrite_level": ("Overwrite lowers the level", "La sobrescritura baja el nivel"),
    "overwrite_mute": ("Overwrite mutes the rule", "La sobrescritura silencia la regla"),
    "overwrite_threshold": ("Overwrite raises the threshold", "La sobrescritura sube el umbral"),
    "preempts": ("Preempts other child rules", "Se adelanta a otras reglas hijas"),
    "sensitive_parent": ("Sensitive parent rule", "Regla padre sensible"),
    "unanchored": ("No stable anchor", "Sin ancla estable"),
    "whole_rule": ("Mutes the whole rule", "Silencia la regla completa"),
}


def _catalog() -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    for key, (en, es) in EVIDENCE_LABELS.items():
        out[f"report.ev.{key}"] = {"en": en, "es": es}
    for (parent, key), (en, es) in SCOPED_LABELS.items():
        out[f"report.ev.{parent}.{key}"] = {"en": en, "es": es}
    for key, (en, es) in VALUE_LABELS.items():
        out[f"report.val.{key}"] = {"en": en, "es": es}
    return out


register(_catalog())
